---
# tasks file for rpi_ugrade

- name: Upgrade kernel
  command: /usr/bin/rpi-update
  register: rpiupdate
  tags:
    - kernel

- name: Update apt cache
  apt: 
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade apt packages
  apt: 
    upgrade: dist

- name: Reboot
  reboot:
    msg: "Reboot triggered by Ansible"
    post_reboot_delay: 10
