---
# tasks file for rpi_ugrade

- name: Upgrade kernel
  command: /usr/bin/rpi-update
  environment:
    SKIP_WARNING: 1
  register: rpiupdate
  changed_when: '"A reboot is needed" in rpiupdate.stdout'
  until: rpiupdate is succeeded
  retries: 3
  notify: reboot
  tags:
    - kernel

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - apt

- name: Upgrade apt packages
  apt:
    upgrade: dist
  register: aptupgrade
  until: aptupgrade is succeeded
  retries: 3
  notify: reboot
  tags:
    - apt

- name: Remove old cache
  apt:
    autoclean: yes
  tags:
    - apt

- name: Remove old deps
  apt:
    autoremove: yes
  notify: reboot
  tags:
    - apt
